[package]
name = "fito"
description = "File System Tool Box"
repository = "https://github.com/emuvi/fito/"
authors = ["Éverton M. Vieira"]
license = "LGPL-3.0-only"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = "2"